after_success:
- .buildscript/deploy_snapshot.sh
android:
  components:
    - tools
    - platform-tools
    - build-tools-26.0.1
    - extra-google-m2repository
    - android-26
before_install:
- wget https://dl.dropboxusercontent.com/u/7897865/apache-maven-3.3.9.zip
- unzip -qq apache-maven-3.3.9.zip
- export M2_HOME=$PWD/apache-maven-3.3.9
- export PATH=$M2_HOME/bin:$PATH
- ./check-missing-assertions.sh
branches:
  except:
  - gh-pages
cache:
  directories:
  - $HOME/.gradle
env:
  global:
  - secure: Z09ZjFkdbvkqpqwzeqz1W9/yPo5IKtsPeRDjplXVeNSZGBLm/YOyzKHZ2htROIrck31Edl/k79fC9P9jaL98VrI4EfzeAg1pXWeQWjqpPoBsyI8kYIf5OmJecOqxFhcE7hTJNI7XxmfzMpMkK8946oegWna9Bf1WWDgW/7iHHgo=
  - secure: icw0oEYt9x2BJ5f1m3nFVV+QkBfDAYs/H6toNeqf/jFuPSbyl+TNTCKTUJj4BKCwmMjLsDSsR3TZi4iKfTQu6x1A8w+2u7gw/wQrFY2tzPqW7/BlOMFEGS/tWpRmw1sLwqQEFd+Fa2Redy2xQywcwFAgjN0zFTfFOQU4UBIcAQo=
jdk:
- oraclejdk8
language: android
notifications:
  email: false
  slack:
    rooms: flakycov:U2MeVOPjdi4up1U793ubeIUZ
    template:
    - Build <%{build_url}|#%{build_number}> (<%{compare_url}|%{commit}>) of %{repository}@%{branch} by %{author} %{result} in %{duration}
    - 'dashbot: %{repository_name} %{build_id}'
script:
- ./gradlew clean check
sudo: false
